config/routes.rb
Rails.application.routes.draw do
 
  resources :pacientes
  resources :solicitacoes
  
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'agenda_aberta' => 'agendas#aberta', :as => 'agenda_aberta'
  get 'solicitacoes/new/:id' => 'solicitacoes#new', :as => 'solicita_agenda'
  get 'solicitacoes/aprovar/:id' => 'solicitacoes#aprovar', :as => 'aprovar_solicitacao'

  get 'municipios/index'
  get 'municipios/estado_municipio', as: 'estado_municipio'

  resources :agendas
  resources :clinicas
  resources :estados
  resources :medicos
  resources :usuario
  resources :especialidades
  resources :instituicoes
  resources :sessions

  root 'principal#index'

end

app/controllers/solicitacoes_controller.rb
class SolicitacoesController < ApplicationController

  # Verifica as permissões dos usuarios
  load_and_authorize_resource

  before_action :set_solicitacao, only: [:show, :edit, :update, :destroy]

  # GET /solicitacoes
  # GET /solicitacoes.json
  def index
    @solicitacoes = Solicitacao.accessible_by(current_ability)
  end

  # GET /solicitacoes/1
  # GET /solicitacoes/1.json
  def show
  end

  # GET /solicitacoes/new
  def new
    @agenda = Agenda.find(params[:id])
    @solicitacao = Solicitacao.new(:instituicao_id => usuario_corrente.instituicao.id, 
      :agenda_id => @agenda.id, :data_emissao => Date.today)
  end

  # GET /solicitacoes/1/edit
  def edit
  end

  # POST /solicitacoes
  # POST /solicitacoes.json
  def create
    @solicitacao = Solicitacao.new(solicitacao_params)
    
    # Inicializa o status como pendente para novas solicitações
    @solicitacao.status = "PE"
    @solicitacao.instituicao_id = usuario_corrente.instituicao.id
    @agenda = Agenda.find(solicitacao_params[:agenda_id])

    respond_to do |format|
      begin 
        @agenda.baixar_agenda
        if @solicitacao.save
          format.html { redirect_to @solicitacao, notice: 'Solicitacão criada com sucesso!' }
          format.json { render :show, status: :created, location: @solicitacao }
        else
          @agenda.estornar_baixa
          format.html { render :new }
          format.json { render json: @solicitacao.errors, status: :unprocessable_entity }
        end
      rescue
        format.html { redirect_to agenda_aberta_path, notice: 'Não existe saldo para a agenda selecionada'}
      end
    end
  end

  # PATCH/PUT /solicitacoes/1
  # PATCH/PUT /solicitacoes/1.json
  def update
    respond_to do |format|
      if @solicitacao.update(update_params)
        format.html { redirect_to @solicitacao, notice: 'Solicitacao atualizada com sucesso!' }
        format.json { render :show, status: :ok, location: @solicitacao }
      else
        format.html { render :edit }
        format.json { render json: @solicitacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solicitacoes/1
  # DELETE /solicitacoes/1.json
  def destroy
    @solicitacao.destroy
    respond_to do |format|
      format.html { redirect_to solicitacoes_url, notice: 'Solicitacao excluida com sucesso!' }
      format.json { head :no_content }
    end
  end

  def aprovar
    @solicitacao = set_solicitacao
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solicitacao
      @solicitacao = Solicitacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def solicitacao_params
      params.require(:solicitacao).permit(:instituicao_id, :agenda_id, :paciente_id, 
        :solicitante, :data_emissao, :descricao)
    end

    def update_params
      params.require(:solicitacao).permit(:data_agendamento, :hora_agendamento, :status)
    end

end

app/helpers/solicitacoes_helper.rb
module SolicitacoesHelper
	def format_time time
		if time != nil
			time.to_s(:time)
		end
	end

	def situacao status
		if  status == "PE"
			"Pendente"
		elsif status == "AP"
			"Aprovada"
		elsif status == "RJ"
			"Rejeitada"
		elsif status == "FS"
			"Finalizada sucesso"
		elsif status == "FN"
			"Finalizada s/ sucesso"
		else
			""
		end
	end
	
end

app/views/solicitacoes/_form.html.erb
<%= form_for @solicitacao, :html => { :class => "form-horizontal solicitacao" } do |f| %>

    <% if @solicitacao.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title">Verifique <%= pluralize(@solicitacao.errors.count, "erro") %> abaixo</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @solicitacao.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <div class="controls">
      <%= f.hidden_field :instituicao_id, :class => 'form-control' %>
    </div>
    <%= error_span(@solicitacao[:instituicao_id]) %>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.hidden_field :agenda_id, :class => 'form-control' %>
    </div>
    <%= error_span(@solicitacao[:agenda_id]) %>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.hidden_field :data_emissao, :class => 'form-control' %>
    </div>
    <%= error_span(@solicitacao[:data_emissao]) %>
  </div>
  <div class="control-group">
    <%= f.label :paciente_id, :class => 'control-label' %>
    <div class="controls">
      <%= collection_select(:solicitacao, :paciente_id, Paciente.all,:id, :nome, {prompt: true}, {:class => 'form-control'}) %>
    </div>
    <%= error_span(@solicitacao[:paciente_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :solicitante, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :solicitante, :class => 'form-control' %>
    </div>
    <%= error_span(@solicitacao[:solicitante]) %>
  </div>
  <div class="control-group">
    <%= f.label :descricao, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :descricao, :class => 'form-control' %>
    </div>
    <%= error_span(@solicitacao[:descricao]) %>
  </div>
  <br>
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            solicitacoes_path, :class => 'btn btn-default' %>

<% end %>

app/views/solicitacoes/aprovar.html.erb
<%- model_class = Solicitacao -%>

<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.aprovacao', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<%= form_for @solicitacao, :html => { :class => "form-horizontal solicitacao" } do |f| %>
  <% if @solicitacao.errors.any? %>
    <div id="error_explanation" class="panel panel-danger">
      <div class="panel-heading">
        <h3>Verifique <%= pluralize(@solicitacao.errors.count, "erro") %> abaixo</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @solicitacao.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <dl class="dl-horizontal">
 		<dt><strong><%= model_class.human_attribute_name(:instituicao_id) %>:</strong></dt>
    <dd><%= @solicitacao.instituicao.nome %></dd>
 		<dt><strong><%= Paciente.human_attribute_name(:nome) + " " + Paciente.model_name.human %>:</strong></dt>
    <dd><%= @solicitacao.paciente.nome %></dd>
    <dt><strong><%= model_class.human_attribute_name(:descricao) %>:</strong></dt>
    <dd><%= @solicitacao.descricao %></dd>
  </dl>

  <div class="control-group">
    <%= f.label :data_agendamento, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :data_agendamento, {:prompt => true}, :class => 'form-control' %>
    </div>
    <%= error_span(@solicitacao[:data_agendamento]) %>
  </div>
  <div class="control-group">
    <%= f.label :hora_agendamento, :class => 'control-label' %>
    <div class="controls">
      <%= f.time_select :hora_agendamento, {:prompt => true}, :class => 'form-control' %>
    </div>
    <%= error_span(@solicitacao[:hora_agendamento]) %>
  </div>
  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.radio_button :status, "AP", {:class => 'radio-inline'} %><%= situacao("AP")%>
      <%= f.radio_button :status, "RJ", {:checked => true, :class => 'radio-inline'} %><%= situacao("RJ")%>
    </div>
    <%= error_span(@solicitacao[:hora_agendamento]) %>
  </div>
  <br>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            solicitacoes_path, :class => 'btn btn-default' %>

<% end %>

app/views/solicitacoes/edit.html.erb
<%- model_class = Solicitacao -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/solicitacoes/index.html.erb
<%- model_class = Solicitacao -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:instituicao_id) %></th>
      <th><%= Medico.human_attribute_name(:nome) + " " + Medico.model_name.human.titleize %></th>
      <th><%= Clinica.human_attribute_name(:nome) + " " + Clinica.model_name.human.titleize%></th>
      <th><%= Paciente.human_attribute_name(:nome) + " " + Paciente.model_name.human.titleize%></th>
      <th><%= model_class.human_attribute_name(:solicitante) %></th>
      <th><%= model_class.human_attribute_name(:data_emissao) %></th>
      <th><%= model_class.human_attribute_name(:data_agendamento) %></th>
      <th><%= model_class.human_attribute_name(:hora_agendamento) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @solicitacoes.each do |solicitacao| %>
      <tr>
        <td><%= link_to solicitacao.instituicao.nome, solicitacao_path(solicitacao)%></td>
        <td><%= solicitacao.agenda.medico.nome %></td>
        <td><%= solicitacao.agenda.clinica.nome %></td>
        <td><%= solicitacao.paciente.nome %></td>
        <td><%= solicitacao.solicitante %></td>
        <td><%= solicitacao.data_emissao %></td>
        <td><%= solicitacao.data_agendamento %></td>
        <td><%= format_time(solicitacao.hora_agendamento) %></td>
        <td><%= situacao(solicitacao.status) %></td>
        <td>
          <%= link_to t('.details', :default => t("helpers.links.details")),
                      solicitacao, :class => 'btn btn-default btn-xs' %>
          <% if usuario_corrente.tipo == "M" %>
            <%= link_to t('.aprovacao', :default => t("helpers.links.aprovacao")), aprovar_solicitacao_path(solicitacao), :class => 'btn btn-primary btn-xs'%>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/solicitacoes/new.html.erb
<%- model_class = Solicitacao -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/solicitacoes/show.html.erb
<%- model_class = Solicitacao -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:instituicao_id) %>:</strong></dt>
  <dd><%= @solicitacao.instituicao.nome %></dd>
  <dt><strong><%= Medico.human_attribute_name(:nome) + " " + Medico.model_name.human %>:</strong></dt>
  <dd><%= @solicitacao.agenda.medico.nome %></dd>
  <dt><strong><%= Clinica.human_attribute_name(:nome) + " " + Clinica.model_name.human %>:</strong></dt>
  <dd><%= @solicitacao.agenda.clinica.nome %></dd>
  <dt><strong><%= Paciente.human_attribute_name(:nome) + " " + Paciente.model_name.human %>:</strong></dt>
  <dd><%= @solicitacao.paciente.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:solicitante) %>:</strong></dt>
  <dd><%= @solicitacao.solicitante %></dd>
  <dt><strong><%= model_class.human_attribute_name(:data_emissao) %>:</strong></dt>
  <dd><%= @solicitacao.data_emissao %></dd>
  <dt><strong><%= model_class.human_attribute_name(:data_agendamento) %>:</strong></dt>
  <dd><%= @solicitacao.data_agendamento %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hora_agendamento) %>:</strong></dt>
  <dd><%= format_time(@solicitacao.hora_agendamento) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= situacao(@solicitacao.status) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descricao) %>:</strong></dt>
  <dd><%= @solicitacao.descricao %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              solicitacoes_path, :class => 'btn btn-default'  %>