config/routes.rb
Rails.application.routes.draw do
 
  resources :pacientes
  resources :solicitacoes
  
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'agenda_aberta' => 'agendas#aberta', :as => 'agenda_aberta'
  get 'solicitacoes/new/:id' => 'solicitacoes#new', :as => 'solicita_agenda'
  get 'solicitacoes/aprovar/:id' => 'solicitacoes#aprovar', :as => 'aprovar_solicitacao'

  get 'municipios/index'
  get 'municipios/estado_municipio', as: 'estado_municipio'

  resources :agendas
  resources :clinicas
  resources :estados
  resources :medicos
  resources :usuario
  resources :especialidades
  resources :instituicoes
  resources :sessions

  root 'principal#index'

end

app/models/especialidade.rb
class Especialidade < ActiveRecord::Base
	has_many :medicos
end

app/controllers/especialidades_controller.rb
class EspecialidadesController < ApplicationController
  
  # Verifica as permissões dos usuarios
  load_and_authorize_resource

  before_action :set_especialidade, only: [:show, :edit, :update, :destroy]

  # GET /especialidades
  # GET /especialidades.json
  def index
    @especialidades = Especialidade.all
  end

  # GET /especialidades/1
  # GET /especialidades/1.json
  def show
  end

  # GET /especialidades/new
  def new
    @especialidade = Especialidade.new
  end

  # GET /especialidades/1/edit
  def edit
  end

  # POST /especialidades
  # POST /especialidades.json
  def create
    @especialidade = Especialidade.new(especialidade_params)

    respond_to do |format|
      if @especialidade.save
        format.html { redirect_to @especialidade, notice: 'Especialidade criado com sucesso!' }
        format.json { render :show, status: :created, location: @especialidade }
      else
        format.html { render :new }
        format.json { render json: @especialidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /especialidades/1
  # PATCH/PUT /especialidades/1.json
  def update
    respond_to do |format|
      if @especialidade.update(especialidade_params)
        format.html { redirect_to @especialidade, notice: 'Especialidade atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @especialidade }
      else
        format.html { render :edit }
        format.json { render json: @especialidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /especialidades/1
  # DELETE /especialidades/1.json
  def destroy
    @especialidade.destroy
    respond_to do |format|
      format.html { redirect_to especialidades_url, notice: 'Especialidade excluída com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_especialidade
      @especialidade = Especialidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def especialidade_params
      params.require(:especialidade).permit(:descricao)
    end
end

app/helpers/especialidades_helper.rb
module EspecialidadesHelper
end

app/views/especialidades/_form.html.erb
<%= form_for(@especialidade) do |f| %>
  <% if @especialidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@especialidade.errors.count, "error") %> prohibited this especialidade from being saved:</h2>

      <ul>
      <% @especialidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_field :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/especialidades/edit.html.erb
<h1>Editing Especialidade</h1>

<%= render 'form' %>

<%= link_to 'Show', @especialidade %> |
<%= link_to 'Back', especialidades_path %>

app/views/especialidades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Especialidades</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @especialidades.each do |especialidade| %>
      <tr>
        <td><%= especialidade.descricao %></td>
        <td><%= link_to 'Show', especialidade %></td>
        <td><%= link_to 'Edit', edit_especialidade_path(especialidade) %></td>
        <td><%= link_to 'Destroy', especialidade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Especialidade', new_especialidade_path %>

app/views/especialidades/new.html.erb
<h1>New Especialidade</h1>

<%= render 'form' %>

<%= link_to 'Back', especialidades_path %>

app/views/especialidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @especialidade.descricao %>
</p>

<%= link_to 'Edit', edit_especialidade_path(@especialidade) %> |
<%= link_to 'Back', especialidades_path %>