config/routes.rb
Rails.application.routes.draw do
 
  resources :pacientes
  resources :solicitacoes
  
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'agenda_aberta' => 'agendas#aberta', :as => 'agenda_aberta'
  get 'solicitacoes/new/:id' => 'solicitacoes#new', :as => 'solicita_agenda'
  get 'solicitacoes/aprovar/:id' => 'solicitacoes#aprovar', :as => 'aprovar_solicitacao'

  get 'municipios/index'
  get 'municipios/estado_municipio', as: 'estado_municipio'

  resources :agendas
  resources :clinicas
  resources :estados
  resources :medicos
  resources :usuario
  resources :especialidades
  resources :instituicoes
  resources :sessions

  root 'principal#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Médico Amigo" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <%= nav_bar fixed: :top, brand: "Médico Amigo", responsive: true do  %>
      
      <%= menu_group do %>
          <%= menu_item "Home", root_path %>
          <% if usuario_corrente %>
            <% if usuario_corrente.tipo == "M" %>          
              <%= menu_item "Solicitações", solicitacoes_path %>
              <%= menu_item "Agendas", agendas_path %>
              <%= menu_item "Clínica", clinicas_path %>
            <% elsif usuario_corrente.tipo == "A" %>
              <%= menu_item "Instituição", instituicoes_path %>
              <%= menu_item "Solicitações", solicitacoes_path %>
              <%= menu_item "Agendas", agendas_path %>
              <%= menu_item "Pacientes", pacientes_path %>
              <%= menu_item "Clínica", clinicas_path %>
            <% elsif usuario_corrente.tipo == "I" %>
              <%= menu_item "Solicitações", solicitacoes_path %>
              <%= menu_item "Agendas", agenda_aberta_path %>
              <%= menu_item "Pacientes", pacientes_path %>
            <%end%>
          <%end%>
      <% end %>

      <%= menu_group pull: :right do %>
          <% if usuario_corrente %>
              <% if usuario_corrente.tipo == "M" %>
                <%= menu_text link_to usuario_corrente.email, edit_medico_path(usuario_corrente.medico.id) %>
              <% elsif usuario_corrente.tipo == "I" %>
                <%= menu_text link_to usuario_corrente.email, edit_instituicao_path(usuario_corrente.instituicao.id) %>
              <% else %>
                <%= menu_text usuario_corrente.email %>
              <% end %>
              <%= menu_item "Sair", log_out_path %>
          <% else %>
              <%= menu_item "Entrar", log_in_path %>
              <%= menu_item "Registrar", new_medico_path %>
          <% end %>
      <% end %>
    <% end %>

    <div class="container">
      <div class="row">
        <div class="col-sm-4">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>